name: DEV CI for x_service

on:
  workflow_dispatch:
  push:
    branches:
    - develop
    paths:
    - 'x_service/**'

jobs:
  test_dotnet_core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['7.x.x']
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
        
    - name: Run Tests
      run: |
        cd x_service
        dotnet restore
        dotnet test
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

  build_push_docker:
    runs-on: ubuntu-latest
    needs: [test_dotnet_core]
    steps:

      - uses: actions/checkout@v2

      # - name: Where are we
      #   run: |
      #     ls
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          #Github will hold the secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract version or SHA
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=${GITHUB_SHA::7}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./x_service  # path to the directory that contains the Dockerfile
          file: ./x_service/Dockerfile  # path to the Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/x_service_dev:${{ env.VERSION }}