name: feature_testing

on:
  push:
    branches:
    - 'feature/*'

jobs:
  test_dotnet_core:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          dotnet: ['7.x.x']
      steps:
      
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
          
      - name: Run Tests
        run: |
          cd x_service
          dotnet restore
          dotnet test
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1