#Service name and the Folder name should be the same on git!
# Remeber to update Service name on yaml file aswell.

# Update the marked areas with x_service to eg. leaderboard_service...

############################
name: PROD CI for x_service 
############################

############################
env:
  SERVICE_NAME: x_service
############################

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
    - master
    tags:
      - 'v*'
    paths:
    # Path needs to be changed to fit Service Folder (As it does not support env)
    ############################
    - 'x_service/**'
    ############################
  workflow_dispatch:

jobs:
  test_dotnet_core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['7.x.x']
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
        
    - name: Run Tests
      run: |
        cd ${{ env.SERVICE_NAME }}
        dotnet restore
        dotnet test
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

  build_push_docker:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    needs: [test_dotnet_core]
    steps:

      - uses: actions/checkout@v2

      # - name: Where are we
      #   run: |
      #     ls
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          #Github will hold the secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version or SHA
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=${GITHUB_SHA::7}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ env.SERVICE_NAME }}  # path to the directory that contains the Dockerfile
          file: ./${{ env.SERVICE_NAME }}/Dockerfile  # path to the Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}_prod:${{ env.VERSION }}